### PR TITLE
fix: remove jasmine from tsconfig types when adding jest

### LINKED ISSUE #1683: [Bug]: jasmine + jest type clash in generated otter apps
### Package name

testing

### Package version

10.1.5

### Reproduction steps

```
npm create @o3r otter-project
cd otter-project
ng g application webapp
# choose preset BASIC, Jest and Playwright when prompted
```

### Current result

After adding Jest, `tsconfig.spec.json` contains types for both Jasmine and Jest:

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "test",
    "types": [
      "jasmine",
      "jest"
    ],
    "lib": [
      "dom",
      "es2020",
      "scripthost"
    ],
    "esModuleInterop": true
  },
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
```

### Expected result

Only Jest and no Jasmine

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "test",
    "types": [
      "jest"
    ],
    "lib": [
      "dom",
      "es2020",
      "scripthost"
    ],
    "esModuleInterop": true
  },
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
```

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by vscaiceanu-1a**
## Related issues

- :bug: Fixes #1683

### CODE REVIEW

**Review by matthieu-crouzet — APPROVED** [review]

File: packages/@o3r/testing/schematics/ng-add/fixture/index.ts [hunk 1]
```diff
@@ -51,6 +51,10 @@ export function updateFixtureConfig(options: { projectName?: string | null | und
         if (tsconfigCompilerOptions.types.indexOf('jest') === -1) {
           tsconfigCompilerOptions.types.push('jest');
         }
+        const jasmineIndex = tsconfigCompilerOptions.types.indexOf('jasmine');
+        if (jasmineIndex !== -1) {
+          tsconfigCompilerOptions.types.splice(jasmineIndex, 1);
+        }
```
Comment (kpanot) [inline packages/@o3r/testing/schematics/ng-add/fixture/index.ts:57]:
```suggestion
        tsconfigCompilerOptions.types = tsconfigCompilerOptions.types?.filter((tsType) => tsType !== 'jasmine');
```

**Review by mrednic-1A — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]
