### PR TITLE
fix(loc): validation on localization metadata

### LINKED ISSUE #1136: [Bug]: No validation on localization metadata file
### Package name

extractors

### Package version

latest

### Reproduction steps

The otter showcase app is able to generate a localization metadata file that does not follow the schema:

```
  {
    "dictionary": true,
    "referenceData": false,
    "key": "o3r-rules-engine-pres.cityName",
    "ref": "o3r-city-name"
  },
```

This is not valid as the "description" attribute is supposed to be required but is missing here.

### Current result

```
  {
    "dictionary": true,
    "referenceData": false,
    "key": "o3r-rules-engine-pres.cityName",
    "ref": "o3r-city-name"
  },
```

is generated with no error

### Expected result

```
  {
    "dictionary": true,
    "referenceData": false,
    "key": "o3r-rules-engine-pres.cityName",
    "ref": "o3r-city-name"
  },
```

should not pass the validation step as it is missing the "description" attribute

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by matthieu-crouzet**
## Proposed change
Validation on localization metadata

## Related issues

- :bug: Fixes #1136

### CODE REVIEW

**Review by cpaulve-1A — DISMISSED** [review]

**Review by fpaul-1A — DISMISSED** [review]

**Review by mrednic-1A — APPROVED** [review]

File: packages/@o3r/localization/builders/localization-extractor/index.ts [hunk 1]
```diff
@@ -73,6 +74,13 @@ export default createBuilder<LocalizationExtractorBuilderSchema>(async (options,
         throw new O3rCliError(`The following translations are invalid: ${translationsWithIssue.map((translation) => translation.key).join(', ')}`);
       }
 
+      validateJson(
+        metadata,
+        require(require.resolve('@o3r/localization/schemas/localization.metadata.schema.json')),
```
Comment (kpanot) [inline packages/@o3r/localization/builders/localization-extractor/index.ts:79]: No needed `require.resolve' in `require`

Should use dynamic import

**Review by kpanot — APPROVED** [review]

**Review by fpaul-1A — APPROVED** [review]

**Review by kpanot — APPROVED** [review]
