### PR TITLE
fix(vscode): add caching to the parsed design token files

### LINKED ISSUE #1490: [Feature]: Improve vscode design token intellisense performance
I think you should add a cache mechanism for the token calculation for the case we will have a large amount of files.
A simple way it to recalculate the Design Token only if one of the file of the glob has changed

_Originally posted by @kpanot in https://github.com/AmadeusITGroup/otter/pull/1479#discussion_r1522411335_

### PR DESCRIPTION
**Pull request by kpanot**
## Proposed change

Add caching to the parsed design token files mechanism

## Related issues

- :rocket: Feature resolves #1490

### CODE REVIEW

File: apps/vscode-extension/src/intellisense/design-token.ts [hunk 1]
```diff
@@ -1,16 +1,33 @@
...
+type DesignTokenCache = {
+  lastExtractionMtime: number;
+  tokenStructure: DesignTokenVariableSet;
+};
+
 const readFile = async (filePat: string) => (await vscode.workspace.fs.readFile(vscode.Uri.parse(filePat))).toString();
 
-const getDesignTokens = async (currentFile?: string) => {
+const getDesignTokens = async (currentFile: string, cache: Map<string, DesignTokenCache>) => {
+  const lastExtractionMtime = (new Date()).getTime();
```
Comment (matthieu-crouzet) [inline apps/vscode-extension/src/intellisense/design-token.ts:14]:
```suggestion
  const lastExtractionMtime = Date.now()
```

**Review by matthieu-crouzet — APPROVED** [review]
Maybe a small comment for `mtime` 
can be hard to understand that m stands for modification

**Review by matthieu-crouzet — APPROVED** [review]

**Review by fpaul-1A — APPROVED** [review]
