### PR TITLE
fix: retrieve dep versions also from devDeps

### LINKED ISSUE #1902: [Bug]: `ng add @o3r/testing` is adding the `jest` dependencies with the version `latest`
### Package name

testing

### Package version

10.0.0+

### Reproduction steps

Create a new application with

```shell
npm create @o3r my-project
cd my-project
npm exec ng g application my-app
```

Add the `@o3r/testing` package:
```shell
npm exec ng add @o3r/testing --project-name my-app
```

### Current result

The dependencies to Jest have been added with the versions `latest`.

### Expected result

The versions of the Jest dependencies should be added aligned with the versions specified in the `@o3r/testing` dependencies.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by vscaiceanu-1a**
## Related issues

- :bug: Fixes #1902

### CODE REVIEW

File: packages/@o3r/schematics/src/utility/dependencies.ts [hunk 1]
```diff
@@ -8,9 +9,14 @@ import { NodeDependency, NodeDependencyType } from '@schematics/angular/utility/
...
-  const packageJsonContent = JSON.parse(fs.readFileSync(packageJsonPath, {encoding: 'utf-8'}));
+  const packageJsonContent = JSON.parse(fs.readFileSync(packageJsonPath, {encoding: 'utf-8'})) as PackageJson & { generatorDependencies: Record<string, string> };
   return packageNames.reduce((acc: Partial<Record<T, string>>, packageName) => {
-    acc[packageName] = packageJsonContent.peerDependencies?.[packageName] || packageJsonContent.generatorDependencies?.[packageName] || packageJsonContent.dependencies?.[packageName] || 'latest';
+    acc[packageName] =
+      packageJsonContent.peerDependencies?.[packageName] ||
+      packageJsonContent.generatorDependencies?.[packageName] ||
+      packageJsonContent.dependencies?.[packageName] ||
+      packageJsonContent.devDependencies?.[packageName] ||
+      'latest';
```
Comment (fpaul-1A) [inline packages/@o3r/schematics/src/utility/dependencies.ts:19]: should we keep that or throw an error ?

Comment (vscaiceanu-1a) [reply packages/@o3r/schematics/src/utility/dependencies.ts:19]: That's a good question. We might consider logging a warning and fallbacking on `latest` so that we don't break the flow.

File: packages/@o3r/schematics/src/utility/dependencies.ts [hunk 2]
```diff
@@ -8,9 +9,14 @@ import { NodeDependency, NodeDependencyType } from '@schematics/angular/utility/
  *  @returns The version range value retrieved from the provided package.json file
  */
 export function getExternalDependenciesVersionRange<T extends string>(packageNames: T[], packageJsonPath: string): Record<T, string> {
-  const packageJsonContent = JSON.parse(fs.readFileSync(packageJsonPath, {encoding: 'utf-8'}));
+  const packageJsonContent = JSON.parse(fs.readFileSync(packageJsonPath, {encoding: 'utf-8'})) as PackageJson & { generatorDependencies: Record<string, string> };
   return packageNames.reduce((acc: Partial<Record<T, string>>, packageName) => {
-    acc[packageName] = packageJsonContent.peerDependencies?.[packageName] || packageJsonContent.generatorDependencies?.[packageName] || packageJsonContent.dependencies?.[packageName] || 'latest';
+    acc[packageName] =
+      packageJsonContent.peerDependencies?.[packageName] ||
+      packageJsonContent.generatorDependencies?.[packageName] ||
```
Comment (kpanot) [inline packages/@o3r/schematics/src/utility/dependencies.ts:16]: the `generatorDependencies` should be the first in the priority order actually (to handle the case we do not want it to be aligned with devDeps for example)

**Review by kpanot — APPROVED** [review]

**Review by fpaul-1A — APPROVED** [review]

File: packages/@o3r/schematics/src/utility/dependencies.ts (hunk 1 above)
Comment (fpaul-1A) [reply packages/@o3r/schematics/src/utility/dependencies.ts]: I was thinking an error would be better to catch the exception directly in the it-tests, but I'm ok with the warning

**Review by mrednic-1A — APPROVED** [review]
