### PR TITLE
fix(rules-engine): add the module when needed

### LINKED ISSUE #1789: [Bug]: Rules engine generators fail to import RulesEngineRunnerModule
### Package name

rules-engine

### Package version

10.0.3

### Reproduction steps

- Generate a workspace and an application using the @o3r/create generator 
- Add an application with `npm run ng g @o3r/workspace:application test`.
- Run `npm run ng add @o3r/rules-engine -- --project-name=test`.
- Generate a component using the `npm run ng g component my-component` command.
- Convert the component into a rules-engine compatible component with the command `npm run ng g rules-engine-to-component -- --path=apps/test/src/components/my-component.component.ts` 

### Current result

The module `RulesEngineRunnerModule`  is neither imported at app nor component level.
image
image

### Expected result

The ng add script should add an import of the RulesEngineRunnerService module in the config.ts (or app.module.ts) in the application. This should not be a manual step.

In a similar fashion, the same module should be imported in the component's import list (in the module or the decorator of the module depending on whether the component is standalone or not) when running the `npm run ng g rules-engine-to-component` command.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by matthieu-crouzet**
## Proposed change
Add the module when needed

## Related issues

- :bug: Fixes #1789

### CODE REVIEW

File: packages/@o3r/rules-engine/schematics/ng-add/index.ts [hunk 1]
```diff
@@ -81,7 +85,30 @@ function ngAddFn(options: NgAddSchematicsSchema): Rule {
         ngAddToRun: depsInfo.o3rPeerDeps
       }),
       ...(options.enableMetadataExtract ? [updateCmsAdapter(options)] : []),
-      await registerDevtools(options)
+      await registerDevtools(options),
+      () => {
+        const moduleFilePath = getAppModuleFilePath(tree, context, options.projectName);
+        if (!moduleFilePath) {
+          return tree;
```
Comment (fpaul-1A) [inline packages/@o3r/rules-engine/schematics/ng-add/index.ts:92]: should we do the equivalent for standalone app ?

Comment (matthieu-crouzet) [reply packages/@o3r/rules-engine/schematics/ng-add/index.ts:92]: It already works (the helper name is not really good I agree)

**Review by fpaul-1A — DISMISSED** [review]

File: packages/@o3r/rules-engine/schematics/ng-add/index.ts [hunk 2]
```diff
@@ -81,7 +85,30 @@ function ngAddFn(options: NgAddSchematicsSchema): Rule {
...
+          true
+        );
+
+        if (isImported(sourceFile, 'RulesEngineRunnerModule', '@o3r/rules-engine')) {
+          return tree;
+        }
+
+        return addRootImport(
+          options.projectName!,
+          ({code, external}) => code`\n${external('RulesEngineRunnerModule', '@o3r/rules-engine')}.forRoot()`
```
[the remark this answers is not in the document]
Comment (matthieu-crouzet) [reply packages/@o3r/rules-engine/schematics/ng-add/index.ts]: image
Doesn't seem to work with `()`

**Review by fpaul-1A — APPROVED** [review]

**Review by kpanot — APPROVED** [review]
