### PR TITLE
fix: install @o3r/ngx-prefetch on app only if dep is present in project package.json

### LINKED ISSUE #1019: [Bug]: Remove the Pre-fetch question from the `ng g application`
### Package name

core, create, workspace

### Package version

9.2.0+

### Reproduction steps

```shell
npm create @o3r my-project
cd my-project
npm exec ng g application my-app
```

### Current result

A question asks if the user want to setup pre-fetch.

### Expected result

Not having this question.
If requested, the prefetch should be detected in the dependencies (or added via `ng add`) as other modules

### Additional comments

The same issue can be applied to `jest` question

### PR DESCRIPTION
**Pull request by matthieu-crouzet**
## Proposed change

Install @o3r/ngx-prefetch on app only if dep is present in project package.json

## Related issues

- :bug: Fixes #1019

### CODE REVIEW

File: packages/@o3r/core/schematics/ng-add/project-setup/index.ts [hunk 1]
```diff
@@ -64,15 +61,11 @@ export const prepareProject = (options: NgAddSchematicsSchema) => async (tree: T
...
-    if (installPrefetch) {
-      const angularVersion = projectPackageJson.dependencies?.['@angular/core'] || projectPackageJson.peerDependencies?.['@angular/core'];
-      const angularMajorVersion = angularVersion?.match(simplifiedSemVerRegexp)?.[1];
-      const ngxPrefetchVersion = angularMajorVersion ? `^${angularMajorVersion}.0.0` : undefined;
-      externalPackagesToInstallWithNgAdd['@o3r/ngx-prefetch'] = ngxPrefetchVersion;
+  if (projectType === 'application') {
+    const ngxPrefetch = '@o3r/ngx-prefetch';
+    const ngxPrefetchVersion = projectPackageJson.dependencies?.[ngxPrefetch];
+    if (typeof ngxPrefetchVersion !== 'undefined') {
+      externalPackagesToInstallWithNgAdd[ngxPrefetch] = ngxPrefetchVersion;
```
Comment (fpaul-1A) [inline packages/@o3r/core/schematics/ng-add/project-setup/index.ts:68]: do we want to keep this at all ? or should it comes from the preset used to create the app ?

**Review by fpaul-1A — APPROVED** [review]

**Review by kpanot — APPROVED** [review]
