### PR TITLE
fix(rules-engine): deprecate executor's prepareRuleset function

### LINKED ISSUE #1044: [Bug]: prepareRuleset method should be private
### Package name

rules-engine

### Package version

9.4.0-alpha

### Reproduction steps

`prepareRuleset` method under `packages/@o3r/rules-engine/src/engine/ruleset-executor.ts` should pe private and not public

### Current result

`prepareRuleset` is public but used only within `ruleset-executor.ts`

### Expected result

`ruleset-executor.ts` to be private

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by kpanot**
## Proposed change

Deprecate executor's prepareRuleset function.
It can be removed in v11 as this function is not made to be used outside of the class (and would not have any effect if done)

## Related issues

- :rocket: Feature resolves #1044

### CODE REVIEW

File: packages/@o3r/rules-engine/src/engine/ruleset-executor.ts [hunk 1]
```diff
@@ -330,4 +320,12 @@ export class RulesetExecutor {
       rulesResultsSubject$: result$
     } as EngineRuleset;
   }
+
+  /**
+   * Plug ruleset to fact streams and trigger a first evaluation
+   * @deprecated This function is not made to be accessible from Outside of the class, will be removed in v11
```
Comment (matthieu-crouzet) [inline packages/@o3r/rules-engine/src/engine/ruleset-executor.ts:326]: I think we can remove it in v10

**Review by matthieu-crouzet — DISMISSED** [review]

File: packages/@o3r/rules-engine/src/engine/ruleset-executor.ts (hunk 1 above)
Comment (mrednic-1A) [reply packages/@o3r/rules-engine/src/engine/ruleset-executor.ts:326]: v10 or v12 :) not v11 :D

File: packages/@o3r/rules-engine/src/engine/ruleset-executor.ts [hunk 2]
```diff
@@ -186,7 +178,6 @@ export class RulesetExecutor {
 
   /**
    * Returns true if the action sets a temporary fact
-   *
```
Comment (cpaulve-1A) [inline packages/@o3r/rules-engine/src/engine/ruleset-executor.ts:189]: Isn't it an eslint rule?

Comment (kpanot) [reply packages/@o3r/rules-engine/src/engine/ruleset-executor.ts:189]: It is

File: packages/@o3r/rules-engine/src/engine/ruleset-executor.ts (hunk 1 above)
Comment (kpanot) [reply packages/@o3r/rules-engine/src/engine/ruleset-executor.ts:326]: v10 really is too short and v12 is a bit too far (for a function that does not make sense to be used).
If the reason to not be v11 is that "we do not make change in v11", that does not make sens to flag it this realese to remove it in v10 neither...
I don't want to argue and change it to `v10` but we may think to be less rigid on that "impair" release.

**Review by fpaul-1A — APPROVED** [review]

File: packages/@o3r/rules-engine/src/engine/ruleset-executor.ts (hunk 1 above)
Comment (mrednic-1A) [reply packages/@o3r/rules-engine/src/engine/ruleset-executor.ts]: ok for me, I see your point

**Review by mrednic-1A — APPROVED** [review]
