### PR TITLE
fix(2396): metadata checks should run on prerelease tags

### LINKED ISSUE #2396: [Bug]: Metadata checks don't take into account prerelease tags
### Package name

extractors

### Package version

11

### Reproduction steps

Run the metadata checks on an application that have prerelease tags:
tags: `1.0.0`, `1.1.0-rc`
Run the metadata checks on the tag `2.0.0`

### Current result

The check is done on tag `1.0.0`

### Expected result

The check should be done on tag `1.1.0-rc`

### Additional comments

This is link the function that we use the get the list of tags `npm view` that doesn't return the prerelease tags when using a range

### PR DESCRIPTION
**Pull request by fpaul-1A**
## Proposed change

- Use `npm view <package> versions` instead of `npm view <package@range> version` to include the prerelease tags
- Extends the `NpmSemverResolver` used for yarn to include prerelease tags

## Related issues

* :bug: Fix resolves #2396

### CODE REVIEW

**Review by kpanot — DISMISSED** [review]

File: packages/@o3r/extractors/src/core/comparator/package-managers-extractors/custom-npm-semver-resolver.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    });
+
+    // If there are versions that aren't deprecated, use them
+    const finalCandidates = noDeprecatedCandidates.length > 0
+      ? noDeprecatedCandidates
+      : candidates;
+
+    finalCandidates.sort((a, b) => {
+      return -a.compare(b);
+    });
```
Comment (kpanot) [inline packages/@o3r/extractors/src/core/comparator/package-managers-extractors/custom-npm-semver-resolver.ts:41]:
```suggestion
    finalCandidates.sort((a, b) => -a.compare(b));
```

File: packages/@o3r/extractors/src/core/comparator/package-managers-extractors/npm-file-extractor.helper.ts [hunk 2]
```diff
@@ -31,18 +31,22 @@ export async function getFilesFromRegistry(packageDescriptor: string, paths: str
   const tempDirPath = join(tmpdir(), tempDirName);
   let extractedFiles: { [key: string]: string } = {};
   mkdirSync(tempDirPath);
+  const [,packageName,packageRange] = sanitizeInput(packageDescriptor).match(/^(.*?)(?:\b@([^@]+))?$/) || [];
```
Comment (kpanot) [inline packages/@o3r/extractors/src/core/comparator/package-managers-extractors/npm-file-extractor.helper.ts:34]: not sure the `@` is forbidden in `prerelease` tag:

```suggestion
  const [,packageName,packageRange] = sanitizeInput(packageDescriptor).match(/^(.*?)(?:\b@(.+))?$/) || [];
```

**Review by kpanot — APPROVED** [review]

**Review by kpanot — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]
