### PR TITLE
fix(design): ng add angular.json updates and file creation

### LINKED ISSUE #1771: [Bug]: ng add @o3r/design does not work
### Package name

design

### Package version

10.2.1

### Reproduction steps

```shell
npm create @o3r my-workspace
cd my-workspace
ng g app webapp
ng add @o3r/design --project-name webapp
```

### Current result

In `angular.json`

- `"useOtterDesignToken": true,` is added for all projects. Shouldn't it be only for webapp?
- `generate-css` builder is not added
Also, no template files are added to the project (design-token.custom.json and theme.scss)

### Expected result

In `angular.json`

- `"useOtterDesignToken": true,` is added only for webapp?
- `generate-css` builder is added for webapp 
Template files are added to the project (design-token.custom.json and theme.scss)

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by kpanot**
## Proposed change

Fix ngAdd schemtics to correctly add @o3r/design package

## Related issues

- :bug: Fixes #1771

### CODE REVIEW

File: packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts
Comment (fpaul-1A) [inline packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts:1]: can you update the it-tests to make sure the files are created ?

File: packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts [hunk 1]
```diff
@@ -8,17 +8,18 @@ import { posix } from 'node:path';
...
 export const registerGenerateCssBuilder = (projectName?: string, taskName = 'generate-css'): Rule => {
-  const registerBuilderRule: Rule = async (tree, {logger}) => {
+  const registerBuilderRule: Rule = async (tree, { logger }) => {
     const { getWorkspaceConfig, registerBuilder } = await import('@o3r/schematics');
-    const workspaceProject = projectName ? getWorkspaceConfig(tree)?.projects[projectName] : undefined;
-    const srcBasePath = workspaceProject?.sourceRoot || (workspaceProject?.root ? posix.resolve(workspaceProject.root, 'src') : '');
-    const themeFile = posix.resolve(srcBasePath, 'style', 'theme.scss');
+    const workspace = getWorkspaceConfig(tree);
+    const workspaceProject = projectName ? workspace?.projects[projectName] : undefined;
+    const srcBasePath = workspaceProject?.sourceRoot || (workspaceProject?.root ? posix.join(workspaceProject.root, 'src') : '.');
```
Comment (cpaulve-1A) [inline packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts:15]: Why is it '.' and not './src' ?

Comment (kpanot) [reply packages/@o3r/design/schematics/ng-add/register-generate-css/register-task.ts:15]: indeed it could be to be more aligned with the case we have the project root

File: packages/@o3r/design/schematics/ng-add/index.spec.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+  });
+
+  it('should generate the template files', async () => {
+    const runner = new SchematicTestRunner('@o3r/design', collectionPath);
+    const tree = await runner.runSchematic('ng-add',{
+      projectName: 'test-project'
+    }, initialTree);
+
+    expect(tree.exists('src/style/design-token.custom.json')).toBe(true);
+    expect(tree.exists('src/style/theme.scss')).toBe(true);
```
Comment (fpaul-1A) [inline packages/@o3r/design/schematics/ng-add/index.spec.ts:24]: can you add these checks on the it-tests as well ?

**Review by fpaul-1A — DISMISSED** [review]

**Review by vscaiceanu-1a — APPROVED** [review]

**Review by fpaul-1A — APPROVED** [review]
