### PR TITLE
fix: wrong path calculation for sdk spec relative path in monorepo

### LINKED ISSUE #2123: [Bug]: Wrong path calculation while creating a sdk in a monorepo with a local spec file
### Package name

workspace

### Package version

11.1

### Reproduction steps

Create a file `repro-spec.yml` with any openapi spec inside
in the same folder rune the following commands
```shell
npm create @o3r repro-monorepo
cd repro-monorepo
npm run ng g sdk --  --name="@repro/sdk" --spec-path="../repro-spec.yml"
```

### Current result

ENOENT: no such file or directory, open 'libs/repro-spec.yml'

### Expected result

The generation should work

### Additional comments

It seems that the `specPath` is computed from the sdk folder instead of from where the command is run.

### PR DESCRIPTION
**Pull request by fpaul-1A**
## Related issues

- :bug: Fixes #2123 
- :rocket: Feature #(issue)

### CODE REVIEW

**Review by mrednic-1A — APPROVED** [review]

File: packages/@o3r/workspace/schematics/sdk/index.ts [hunk 1]
```diff
@@ -48,6 +48,10 @@ function generateSdkFn(options: NgGenerateSdkSchema): Rule {
 
     const packageManager = getPackageManager({ workspaceConfig });
     const specExtension = options.specPackagePath ? path.extname(options.specPackagePath) : '.yaml';
+    // If spec path is relative to process.cwd, we need to make it relative to the project root
+    if (options.specPath?.startsWith('.')) {
```
Comment (kpanot) [inline packages/@o3r/workspace/schematics/sdk/index.ts:52]: not covering all the cases, why not using `options.specPath && !path.isAbsolute(options.specPath)` ?

**Review by kpanot — APPROVED** [review]

File: packages/@o3r/workspace/schematics/index.it.spec.ts [hunk 2]
```diff
@@ -31,8 +33,31 @@ describe('new otter workspace', () => {
...
+    const { workspacePath, isInWorkspace, untouchedProjectsPaths } = o3rEnvironment.testEnvironment;
+    const sdkPath = path.posix.join('libs', 'my-sdk-sdk');
+    const execAppOptions = {...getDefaultExecSyncOptions(), cwd: workspacePath};
+    await fs.copyFile(path.join(mocksFolder, 'easy-spec.yaml'), path.join(workspacePath, 'local-spec.yaml'));
+    packageManagerExec({script: 'ng', args: [
+      'g',
+      'sdk',
+      '@my-sdk/sdk',
+      '--spec-path', './local-spec.yaml'
+    ]}, execAppOptions);
```
Comment (matthieu-crouzet) [inline packages/@o3r/workspace/schematics/index.it.spec.ts:46]:
```suggestion
    expect(() => packageManagerExec({script: 'ng', args: [
      'g',
      'sdk',
      '@my-sdk/sdk',
      '--spec-path', './local-spec.yaml'
    ]}, execAppOptions)).not.toThrow();
```

File: packages/@o3r/workspace/schematics/index.it.spec.ts [hunk 3]
```diff
@@ -48,6 +73,7 @@ describe('new otter workspace', () => {
     untouchedProjectsPaths.forEach(untouchedProject => {
       expect(diff.all.some(file => file.startsWith(path.posix.relative(workspacePath, untouchedProject)))).toBe(false);
     });
+    expect(diff.added).toContain(path.posix.join(sdkPath, 'open-api.yaml'));
```
Comment (matthieu-crouzet) [inline packages/@o3r/workspace/schematics/index.it.spec.ts:76]: We could also check that we have the model files generated no ?

File: packages/@o3r/workspace/schematics/sdk/index.ts (hunk 1 above)
Comment (fpaul-1A) [reply packages/@o3r/workspace/schematics/sdk/index.ts:52]: I didn't use `path.isAbsolute` because `options.specPath` can also be an URL, but indeed `startsWith('.')` is not enough

**Review by kpanot — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]
