### PR TITLE
fix: remove the dependency of schematics to dev-tools

### LINKED ISSUE #332: [Bug]: ng add @o3r/core doesn't work
### Package name

core

### Package version

8.1.6

### Reproduction steps

- create a new Angular app with `ng new`
- run `ng add @o3r/core`  in the app folder

### Current result

```shell
$ ng add @o3r/core
ℹ Using package manager: npm
✔ Found compatible package version: @o3r/core@8.1.6.
✔ Package information loaded.

The package @o3r/core@8.1.6 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
require() of ES Module /Users/vscaiceanu/workspace/otter/otter-app/node_modules/globby/index.js from /Users/vscaiceanu/workspace/otter/otter-app/node_modules/@o3r/dev-tools/src/utils/jest.helpers.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/vscaiceanu/workspace/otter/otter-app/node_modules/globby/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

### Expected result

```shell
? Activate prefetch builder to generate prefetcher JavaScript file ? (Y/n) 
```

### Additional comments

As a workaround you can run the command again and the schematics will be executed.

```shell
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.2.8
Node: 18.14.1
Package Manager: npm 9.5.0
OS: darwin arm64

Angular: 15.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            7.8.1
typescript                      4.9.5
```

### PR DESCRIPTION
**Pull request by kpanot**
## Proposed change

Removing dependency of schematics to the dev-tools to avoid ESM / CommonJs clash

## Related issues

- :bug: Fixes #332

### CODE REVIEW

**Review by matthieu-crouzet — APPROVED** [review]

File: packages/@o3r/dev-tools/src/utils/check-peer-deps.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ export function getPackagesToInstallOrUpdate(packageName: string) {
 /**
  * Log an instruction with the packages to install or update to match a package peer dependencies
  *
+ * @deprecated use `checkPackagesRule` or `checkPackagesToInstallOrUpdate` functions exposed by `@o3r/schematics` instead. Will be removed in Otter v10
```
Comment (vscaiceanu-1a) [inline packages/@o3r/dev-tools/src/utils/check-peer-deps.ts:70]: I think this method is only used in `packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts` where you replaced it with the new one. In this case, why not removing it completely from here?

File: packages/@o3r/schematics/package.json [hunk 2]
```diff
@@ -55,6 +54,7 @@
     "@nrwl/js": "~15.9.0",
     "@nrwl/linter": "~15.9.0",
     "@o3r/build-helpers": "workspace:^",
+    "@o3r/dev-tools": "workspace:^",
```
Comment (vscaiceanu-1a) [inline packages/@o3r/schematics/package.json:57]: shouldn't this PR remove the dependency?

File: packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts [hunk 3]
```diff
@@ -1,15 +1,124 @@
...
+}
+
+/**
+ * Log an instruction with the packages to install or update to match a package peer dependencies
+ *
+ * @param packageName
+ * @param angularJsonString
+ * @param logger
+ */
+export function checkPackagesToInstallOrUpdate(packageName: string, logger: LoggerApi, angularJsonString?: string | null) {
```
Comment (vscaiceanu-1a) [inline packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts:84]: if not used outside this file, is it worth exporting it?

File: packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts [hunk 4]
```diff
@@ -1,15 +1,124 @@
...
+  });
+  return { packagesToInstall, packagesWrongVersion };
+}
+
+/**
+ * Log an instruction with the packages to install or update to match a package peer dependencies
+ *
+ * @param packageName
+ * @param angularJsonString
+ * @param logger
```
Comment (vscaiceanu-1a) [inline packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts:82]: wrong params order

File: packages/@o3r/dev-tools/src/utils/check-peer-deps.ts (hunk 1 above)
Comment (kpanot) [reply packages/@o3r/dev-tools/src/utils/check-peer-deps.ts:70]: Because it is exposed by the package, so removing it would be a breaking change (even if on our side we you it only once :S)

File: packages/@o3r/schematics/package.json (hunk 2 above)
Comment (kpanot) [reply packages/@o3r/schematics/package.json:57]: It is now a devDep, used only in test purpose

File: packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts (hunk 4 above)
Comment (kpanot) [reply packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts:82]: There is no order in JsDoc parameters, this is the reason why it is named :)

File: packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts (hunk 3 above)
Comment (kpanot) [reply packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts:84]: I hesitated by I finally kept the export because it was exported before and because it was not a big deal to do so

Comment (vscaiceanu-1a) [reply packages/@o3r/schematics/src/rule-factories/check-packages-peers/index.ts:84]: Well, this way, next time we want to remove it, we will have to deprecate it because we won't know if anyone else is using it. Let's keep it as a private method and, if we ever need it outside, we can export it?

**Review by vscaiceanu-1a — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]
