### PR TITLE
fix: Use tagname for mat-option in fixtures

### LINKED ISSUE #520: [Bug]: Autocomplete fixtures do not work with MDC
### Package name

testing

### Package version

8.0.x

### Reproduction steps

Try to test an autocomplete in fixtures

### Current result

You get a timeout as the selector used is incorrect for mdc

### Expected result

The selector should be correct

### Additional comments

The tagname allows to target both MDC and legacy

### PR DESCRIPTION
**Pull request by rglearns**
## Proposed change

Using mat option tagname instead of class as the class changed with MDC 

## Related issues

- :bug: Fixes #520 
- :rocket: Feature #(issue)

### CODE REVIEW

**Review by kpanot — APPROVED** [review]

File: packages/@o3r/testing/src/core/playwright/angular-materials/autocomplete-material.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export class MatAutocomplete extends O3rElement implements MatAutocompleteProfil
     await this.setValue(value);
     await this.click();
     const element = this.sourceElement.page;
-    const matOptions = element.locator('.mat-option');
+    const matOptions = element.locator('mat-option');
```
Comment (matthieu-crouzet) [inline packages/@o3r/testing/src/core/playwright/angular-materials/autocomplete-material.ts:19]: Shouldn't we put `.mat-option, mat-option` to not break the previous behaviour ?

Comment (rglearns) [reply packages/@o3r/testing/src/core/playwright/angular-materials/autocomplete-material.ts:19]: The tag would select both mdc and legacy and imo is more future proof as classes can change with each angular release

Comment (matthieu-crouzet) [reply packages/@o3r/testing/src/core/playwright/angular-materials/autocomplete-material.ts:19]: as we are on a released version

Comment (rglearns) [reply packages/@o3r/testing/src/core/playwright/angular-materials/autocomplete-material.ts]: done

**Review by kpanot — APPROVED** [review]

**Review by fpaul-1A — APPROVED** [review]
