### PR TITLE
fix: #3209 Use correct DF component for date-picker

### LINKED ISSUE #3209: [Bug]: Wrong usage of DF textbox on `forms` page
### Application name

Showcase

### Version

12.2.0

### Reproduction steps

- Go to https://amadeusitgroup.github.io/otter/#/forms
- Focus Date of Birth field

### Current result

Image

### Expected result

Same display of other DF textboxes on focus

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by cpaulve-1A**
## Proposed change
Rework date picker to follow DF.

## Related issues
:bug: Fix resolves #3209

### CODE REVIEW

File: apps/showcase/src/components/utilities/date-picker-input-hebrew/date-picker-input-hebrew-pres.component.ts [hunk 1]
```diff
@@ -83,8 +83,7 @@ export class DatePickerHebrewInputPresComponent implements ControlValueAccessor,
   public selectedDate = signal<NgbDate | null>(null);
 
   /** @inheritDoc */
-  @Input()
-  public id!: string;
+  public id = input('');
```
Comment (matthieu-crouzet) [inline apps/showcase/src/components/utilities/date-picker-input-hebrew/date-picker-input-hebrew-pres.component.ts:86]:
```suggestion
  public id = input.required<string>();
```

File: apps/showcase/src/components/utilities/date-picker-input/date-picker-input-pres.component.ts [hunk 2]
```diff
@@ -42,30 +44,30 @@ import {
...
-  private onChanges!: (val: string) => void;
-
   /** Disabled state of the date-picker */
   public isDisabled = signal(false);
 
   /** Internal selected date by NgBootstrap */
-  public selectedDate = signal<NgbDate | null>(null);
+  public dateControl = new FormControl<NgbDateStruct | undefined>(undefined, { nonNullable: true });
+  /** @inheritDoc */
+  public id = input('');
```
Comment (matthieu-crouzet) [inline apps/showcase/src/components/utilities/date-picker-input/date-picker-input-pres.component.ts:53]:
```suggestion
  public id = input.required<string>();
```

File: apps/showcase/src/components/utilities/date-picker-input/date-picker-input-pres.component.ts [hunk 3]
```diff
@@ -42,30 +44,30 @@ import {
...
 
   /** @inheritDoc */
-  @Input()
-  public id!: string;
+  public label = input('');
```
Comment (matthieu-crouzet) [inline apps/showcase/src/components/utilities/date-picker-input/date-picker-input-pres.component.ts:56]:
```suggestion
  public label = input.required<string>();
```

File: apps/showcase/src/components/utilities/date-picker-input/date-picker-input-pres.context.ts [hunk 4]
```diff
@@ -7,7 +10,9 @@ import type {
  */
 export interface DatePickerInputPresContextInput {
   /** ID of the html element used for selection */
-  id: string;
+  id: InputSignal<string>;
+  /** Label of the datepicker */
+  label?: InputSignal<string>;
```
Comment (matthieu-crouzet) [inline apps/showcase/src/components/utilities/date-picker-input/date-picker-input-pres.context.ts:15]:
```suggestion
  label: InputSignal<string>;
```
as you set the input as required
```
public label = input.required<string>();

**Review by fpaul-1A — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]
