### PR TITLE
fix: o3r/core as devDep for new Otter libs

### LINKED ISSUE #1717: [Bug]: build is failing for new Otter library
### Package name

core, workspace

### Package version

10.2.1

### Reproduction steps

```shell
npm create @o3r otter-project
cd otter-project
ng g library somelib
npm run ng build somelib
```

### Current result

```shell

------------------------------------------------------------------------------
Building entry point 'somelib'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
error TS5090: Non-relative paths are not allowed when 'baseUrl' is not set. Did you forget a leading './'?
```

Adding `baseUrl` by hand leads to another error:

`Dependency @o3r/core must be explicitly allowed using the "allowedNonPeerDependencies" option.`

### Expected result

Build success

### Additional comments

The second error comes from the fact that `@o3r/core` is added as `dependency` and not `devDependency` on the generated library.

### PR DESCRIPTION
**Pull request by vscaiceanu-1a**
## Related issues

- :bug: Fixes #1717

### CODE REVIEW

File: packages/@o3r/workspace/schematics/library/index.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ function generateModuleFn(options: NgGenerateModuleSchema): Rule {
         inManifest: [
           {
             range: `${options.exactO3rVersion ? '' : '~'}${ownPackageJsonContent.version!}`,
-            types: [NodeDependencyType.Default]
+            types: [NodeDependencyType.Dev]
```
Comment (matthieu-crouzet) [inline packages/@o3r/workspace/schematics/library/index.ts:49]: Why not peerDep ?

Comment (vscaiceanu-1a) [reply packages/@o3r/workspace/schematics/library/index.ts:49]: `setupDependencies` will add the package in the root package.json as well and we do not want to add peerDeps there.

**Review by fpaul-1A — DISMISSED** [review]

**Review by matthieu-crouzet — APPROVED** [review]

**Review by fpaul-1A — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]
