### PR TITLE
fix(metric): avoid awaiting the metric report call

### LINKED ISSUE #1201: [Feature]: Otter cli metrics
### Context

Based on the same idea than https://angular.io/cli/analytics
As an Otter developer, I would be able to collect data to see what are the generators/builders used by our users, how they are used, if they encounter some issues, errors etc so I can provide a better user experience (bugfixes) and prioritize new features for the future as well.

### Proposal

A wrapper method to create a generator/builder that will retrieve all needed data and send those to a server.

- [x] Wrapper methods https://github.com/AmadeusITGroup/otter/pull/1183
- [x] Service to call the server
   - [ ] Do not throw error if the call fail

### PR DESCRIPTION
**Pull request by kpanot**
## Proposed change

Avoid awaiting the metric report call

## Related issues

- :bug: Fixes #1201

### CODE REVIEW

File: packages/@o3r/telemetry/src/builders/index.ts [hunk 1]
```diff
@@ -35,38 +34,36 @@ export const createBuilderWithMetrics: BuilderWrapper = (builderFn, sendData = d
...
+                name: context.target.target,
+                projectName: context.target.project,
+                configuration: context.target.configuration
+              }
+            } : {}
+          )
+        },
+        error
+      };
+      context.logger.debug(JSON.stringify(data, null, 2));
```
Comment (fpaul-1A) [inline packages/@o3r/telemetry/src/builders/index.ts:61]: we should probably remove this

File: packages/@o3r/telemetry/src/schematics/index.ts [hunk 2]
```diff
@@ -31,28 +33,26 @@ export const createSchematicWithMetrics: SchematicWrapper =
...
+        options,
+        interactive: context.interactive
+      };
+      const data: SchematicMetricData = {
+        environment,
+        schematic,
+        duration,
+        error
+      };
+      context.logger.debug(JSON.stringify(data, null, 2));
```
Comment (fpaul-1A) [inline packages/@o3r/telemetry/src/schematics/index.ts:50]: we should probably remove this (or add a message)

**Review by fpaul-1A — APPROVED** [review]

File: packages/@o3r/telemetry/src/builders/index.ts (hunk 1 above)
Comment (matthieu-crouzet) [reply packages/@o3r/telemetry/src/builders/index.ts:61]: It was more for us when we run the command with `--verbose`
