### PR TITLE
fix: copy specs local file refs

### LINKED ISSUE #2014: [Bug]: openapi-generator 7.4.0 fails to resolve refs to files
### Package name

schematics

### Package version

11.0.1

### Reproduction steps

_You can ask me in Teams and I'll provide a reproduction .zip_

__Step 1: create models__
```shell
OTTER_ROOT=todefine
mkdir ama-sdk-repro && cd ama-sdk-repro && mkdir models
cp $OTTER_ROOT/packages/@ama-sdk/showcase-sdk/openapi.yml ./models/pet-specs-untouched.yaml
cp ./models/pet-specs-untouched.yaml ./models/pet-specs-split.yaml
touch ./models/pet-response.yaml
```

__Step 2: Manually modify ``pet-specs-split.yaml``__

Modify the ``paths./pet.post.responses.'200'`` to point to a ``components.response`` ``ok-pet``:
```yaml
  /pet:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      description: Add a new pet to the store
      operationId: addPet
      responses:
        '200':
          $ref: '#/components/responses/ok-pet'
```
Create the ``components.response`` ``ok-pet``:
```yaml
  responses:
    ok-pet:
      description: Successful Pet operation
      content:
        application/xml:
          schema:
            $ref: './pet-response.yaml'
        application/json:
          schema:
            $ref: './pet-response.yaml'
```

In ``pet-response.yaml``, modify the refs to point to ``pet-specs-split.yaml#/components``. Also add a title:
```yaml
x-swagger-router-model: io.swagger.petstore.model.Pet
title: Pet
type: object
required:
  - name
  - photoUrls
properties:
  id:
    type: integer
    format: int64
    example: 10
  name:
    type: string
    example: doggie
  category:
    $ref: './pet-specs-split.yaml#/components/schemas/Category'
  photoUrls:
    type: array
    xml:
      wrapped: true
    items:
      type: string
      xml:
        name: photoUrl
  tags:
    type: array
    xml:
      wrapped: true
    items:
      $ref: './pet-specs-split.yaml#/components/schemas/Tag'
      xml:
        name: tag
  status:
    type: string
    description: pet status in the store
    enum:
      - available
      - pending
      - sold
xml:
  name: pet
```

__Step 3: generate SDKs for version 9.6.x and 11.0.x__
```bash
npm create @ama-sdk@9.6.3 typescript sdk-otter-9 -- --spec-path ./models/pet-specs-untouched.yaml
npm create @ama-sdk typescript sdk-otter-11 -- --spec-path ./models/pet-specs-untouched.yaml
```
_Note_: I had troubles with ``--spec-path``  and ``--generator-key`` on v11 and had to manually modify the scripts in ``package.json``.

Also, I've duplicated the ``spec:regen`` script so that it targets both split & untouched specs:
```text
// v9
"spec:regen:untouched": "npm run generate -- --spec-path ../models/pet-specs-untouched.yaml && npm run clear-index",
"spec:regen:split": "npm run generate -- --spec-path ../models/pet-specs-split.yaml && npm run clear-index",

// v11
"spec:regen:untouched": "npm run generate -- --spec-path ../models/pet-specs-untouched.yaml --generator-key sdk-otter-11 && amasdk-clear-index",
"spec:regen:split": "npm run generate -- --spec-path ../models/pet-specs-split.yaml --generator-key sdk-otter-11 && amasdk-clear-index",
```

### Current result

- ``npm run spec:regen:untouched`` works for both v9 and v11
- ``npm run spec:regen:split`` works for v9
- ``npm run spec:regen:split`` fails for v11 with below exception

```log
Did set selected version to 7.4.0
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while resolving:
java.lang.RuntimeException: Unable to load RELATIVE ref: ./pet-response.yaml path: /home/fhamelin/git_clones/ama-sdk-repro/sdk-otter-11
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:220)
        at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:150)
        at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:88)
        at io.swagger.v3.parser.processors.SchemaProcessor.processReferenceSchema(SchemaProcessor.java:236)
        at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:60)
        at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:56)
        at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:86)
        at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:88)
        at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:72)
        at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:59)
        at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:238)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:181)
        at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:97)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:686)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: Could not find ./pet-response.yaml on the classpath
        at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:33)
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:214)
        ... 18 common frames omitted
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./pet-response.yaml
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./pet-response.yaml
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./pet-response.yaml
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./pet-response.yaml
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 2
Errors:
        -Unable to load RELATIVE ref: ./pet-response.yaml path: /home/fhamelin/git_clones/ama-sdk-repro/sdk-otter-11
Warnings:
        -Unable to load RELATIVE ref: ./pet-response.yaml path: /home/fhamelin/git_clones/ama-sdk-repro/sdk-otter-11

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Error: OpenApiGeneratorCli failed to run OpenApiGenerator with command 'openapi-generator-cli generate --custom-generator=/home/fhamelin/git_clones/ama-sdk-repro/sdk-otter-11/node_modules/@ama-sdk/schematics/schematics/typescript/core/openapi-codegen-typescript/target/typescriptFetch-openapi-generator.jar -g typescriptFetch -i open-api.yaml -o .
```

### Expected result

``npm run spec:regen:split`` should work on v11 (and v10 which I haven't tried)

### Additional comments

- Using JDK ``11.0.14.1-jbr``
- For the failing case, it uses openapi-generator ``7.4.0``. Tried to upgrade to openapi-generator ``7.7.0`` but same issue
- The working case uses openapi-generator ``6.6.0``
- When generating the ``typescriptFetch-openapi-generator.jar`` for ``7.7.0``, I had to modify the file ``AbstractTypeScriptClientCodegen`` because they moved the ``getSchemaItems`` method to ``ModelUtils`` (see [DefaultCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java)). Note that the exception above has warnings for ``ModelUtils``, so it could be related.
- This kind of issue seems to be reccurrent with openapi-generator. It gets fixed then breaks again:
https://github.com/OpenAPITools/openapi-generator/issues/17554
https://github.com/OpenAPITools/openapi-generator/issues/18429

### PR DESCRIPTION
**Pull request by fpaul-1A**
## Proposed change

When we copy the spec file before generating the SDK we are breaking the local relative paths referenced in the file.
The proposed change is to copy all the referenced files inside the SDK in a folder `./spec-local-references/` to have them versioned.
We also update the local references in the spec to look for these files.

## Related issues

- :bug: Fixes #2014 
- :rocket: Feature #(issue)

### CODE REVIEW

File: packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+  });
+}
+
+/**
+ * Copy the local files referenced in the input spec file to the output directory
+ * @param specFilePath
+ * @param outputDirectory
+ */
+export async function copyReferencedFiles(specFilePath: string, outputDirectory: string) {
+  const dedupe = (paths: string[]) =>
```
Comment (pginoux-1A) [inline packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts:67]: For each string from paths, the findIndex method will return the first element in the array to match the comparison, but wouldn't one iteration be enough here to dedupe the array ?

File: packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts [hunk 2]
```diff
@@ -0,0 +1,96 @@
+import { existsSync } from 'node:fs';
+import { copyFile, mkdir, readFile, rm } from 'node:fs/promises';
+import { dirname, join, normalize, posix, relative, resolve } from 'node:path';
+
+const refMatcher = /\B['"]?[$]ref['"]?\s*:\s*([^#\n]+)/g;
```
Comment (kpanot) [inline packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts:5]:
```suggestion
const refMatcher = /\B['"]?[$]ref['"]?\s*:[\n\s|]*([^#\n]+)/g;
```

File: packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.spec.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
+import { cleanVirtualFileSystem, useVirtualFileSystem } from '@o3r/test-helpers';
+import { readFile } from 'node:fs/promises';
+import { dirname, join } from 'node:path';
+
+describe('Copy Referenced Files', () => {
```
Comment (kpanot) [inline packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.spec.ts:5]: You should add UT for `updateLocalRelativeRefs` as well

File: packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts (hunk 2 above)
Comment (cpaulve-1A) [reply packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts:5]: image
Not sure this is a valid use-case

File: packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts (hunk 1 above)
Comment (cpaulve-1A) [reply packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts:67]: You could use maps to avoid the double iteration

Comment (mrednic-1A) [reply packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts:67]: `const dedupe = (paths: string[]) => ([...new Set(paths)]);` shouldn't be enough ?

File: packages/@ama-sdk/schematics/schematics/typescript/core/index.ts [hunk 4]
```diff
@@ -153,10 +154,19 @@ function ngGenerateTypescriptSDKFn(options: NgGenerateTypescriptSDKCoreSchematic
...
     if (URL.canParse(generatorOptions.specPath) && (new URL(generatorOptions.specPath)).protocol.startsWith('http')) {
       specContent = await (await fetch(generatorOptions.specPath)).text();
+      specContent = updateLocalRelativeRefs(specContent, path.dirname(generatorOptions.specPath));
     } else {
       const specPath = path.isAbsolute(generatorOptions.specPath) || !options.directory ?
         generatorOptions.specPath : path.join(options.directory, generatorOptions.specPath);
       specContent = readFileSync(specPath, {encoding: 'utf-8'}).toString();
+
+      if (path.relative(process.cwd(), specPath).startsWith('..')) {
+        // TODO would be better to create files on tree instead of FS
```
Comment (kpanot) [inline packages/@ama-sdk/schematics/schematics/typescript/core/index.ts:164]: Indeed. Can you please create an issue associated to it (and add its ref into the comment)?

Comment (mrednic-1A) [reply packages/@ama-sdk/schematics/schematics/typescript/core/index.ts:164]: https://github.com/AmadeusITGroup/otter/issues/2078

**Review by cpaulve-1A — APPROVED** [review]

File: packages/@ama-sdk/schematics/schematics/typescript/core/index.ts (hunk 4 above)
Comment (kpanot) [reply packages/@ama-sdk/schematics/schematics/typescript/core/index.ts:164]: can you refer your issue in your `todo` comment?

Comment (mrednic-1A) [reply packages/@ama-sdk/schematics/schematics/typescript/core/index.ts:164]: yes, the link is on the line below. I preferred the full link because it can be open directly from the IDE with ctrl+click

**Review by kpanot — APPROVED** [review]

File: packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts (hunk 1 above)
Comment (fpaul-1A) [reply packages/@ama-sdk/schematics/schematics/typescript/core/helpers/copy-referenced-files.ts]: some path are equivalent but not equal as strings 
say you have
```
dirA
|  spec.yml
|  ref.yml
```
the path to ref.yml can be `./ref.yml` or `../dirA/ref.yml`, that's why I was not just using a Set
