### PR TITLE
fix: enforce install if dependencies have ng add

### LINKED ISSUE #2766: [Bug]: adding eslint-config-otter when adding @o3r/workspace fails on a project with eslint
### Package name

workspace

### Package version

11.5.0

### Reproduction steps

```shell
ng new --no-create-application my-workspace
cd my-workspace
npm install -D eslint
ng add @o3r/workspace # make sure angular and otter version are aligned to avoid peer dep errors

You already have ESLint installed. Would you like to add Otter config rules for ESLint?
Otherwise, you can add them later via this command: ng add @o3r/eslint-config-otter Yes
```

### Current result

Collection "@o3r/eslint-config-otter" cannot be resolved.

### Expected result

Adds workspace along with Otter eslint correctly. 

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by vscaiceanu-1a**
## Proposed change

Perform the install if a dependency has an `ng-add` schematics *and* is not installed yet, even if the parent schematics has `skipInstall` to `true` (which is the default value).

## Related issues

* :bug: Fix resolves #2766

### CODE REVIEW

File: packages/@o3r/schematics/src/rule-factories/ng-add/dependencies.ts [hunk 1]
```diff
@@ -170,7 +170,18 @@ export const setupDependencies = (options: SetupDependenciesOptions): Rule => {
     const ngAddToRun = new Set(Object.keys(options.dependencies)
       .filter((dep) => options.ngAddToRun?.some((pattern) => typeof pattern === 'string' ? pattern === dep : pattern.test(dep))));
     const requiringInstallList = new Set(Object.entries(options.dependencies).filter(([, { requireInstall }]) => requireInstall).map(([dep]) => dep));
-    const isInstallNeeded = () => options.skipInstall === undefined ? (ngAddToRun.size > 0 || requiringInstallList.size > 0) : !options.skipInstall;
+    const isPackageInstalled = (packageName: string): boolean => {
```
Comment (kpanot) [inline packages/@o3r/schematics/src/rule-factories/ng-add/dependencies.ts:173]: this function already exists in `src/utilities`

**Review by mrednic-1A — APPROVED** [review]

**Review by matthieu-crouzet — APPROVED** [review]

**Review by kpanot — APPROVED** [review]
